// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function eval_core(core) {
  if (core.tag) {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "demo.ml",
            67,
            60
          ]
        ];
  } else {
    return /* Error */Block.__(1, ["TODO"]);
  }
}

function intersperse_after(list, el) {
  if (list) {
    var match = list[1];
    var list_el = list[0];
    if (match) {
      return /* :: */[
              list_el,
              /* :: */[
                el,
                intersperse_after(/* :: */[
                      match[0],
                      match[1]
                    ], el)
              ]
            ];
    } else {
      return /* :: */[
              list_el,
              /* :: */[
                el,
                /* [] */0
              ]
            ];
    }
  } else {
    return /* [] */0;
  }
}

exports.eval_core = eval_core;
exports.intersperse_after = intersperse_after;
/* No side effect */
