// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function message(s) {
  switch (s) {
    case 5 : 
        return "<YOUR SYNTAX ERROR MESSAGE HERE 4>\n";
    case 6 : 
        return "<YOUR SYNTAX ERROR MESSAGE HERE 3>\n";
    case 10 : 
        return "<YOUR SYNTAX ERROR MESSAGE HERE 1>\n";
    case 15 : 
        return "<YOUR SYNTAX ERROR MESSAGE HERE 2>\n";
    case 7 : 
    case 8 : 
    case 9 : 
    case 12 : 
    case 13 : 
    case 14 : 
    case 16 : 
    case 17 : 
    case 18 : 
    case 22 : 
    case 25 : 
    case 26 : 
    case 38 : 
    case 39 : 
    case 41 : 
    case 43 : 
    case 45 : 
    case 46 : 
    case 52 : 
    case 55 : 
    case 56 : 
    case 57 : 
    case 58 : 
    case 59 : 
    case 63 : 
    case 69 : 
    case 70 : 
    case 71 : 
    case 72 : 
    case 73 : 
    case 75 : 
    case 76 : 
    case 79 : 
    case 80 : 
    case 81 : 
    case 82 : 
    case 85 : 
    case 86 : 
    case 87 : 
    case 88 : 
    case 91 : 
    case 94 : 
    case 95 : 
    case 96 : 
    case 97 : 
    case 98 : 
    case 99 : 
    case 101 : 
    case 104 : 
    case 105 : 
    case 106 : 
    case 107 : 
    case 108 : 
        throw Caml_builtin_exceptions.not_found;
    case 0 : 
    case 1 : 
    case 2 : 
    case 3 : 
    case 4 : 
    case 11 : 
    case 19 : 
    case 20 : 
    case 21 : 
    case 23 : 
    case 24 : 
    case 27 : 
    case 28 : 
    case 29 : 
    case 30 : 
    case 31 : 
    case 32 : 
    case 33 : 
    case 34 : 
    case 35 : 
    case 36 : 
    case 37 : 
    case 40 : 
    case 42 : 
    case 44 : 
    case 47 : 
    case 48 : 
    case 49 : 
    case 50 : 
    case 51 : 
    case 53 : 
    case 54 : 
    case 60 : 
    case 61 : 
    case 62 : 
    case 64 : 
    case 65 : 
    case 66 : 
    case 67 : 
    case 68 : 
    case 74 : 
    case 77 : 
    case 78 : 
    case 83 : 
    case 84 : 
    case 89 : 
    case 90 : 
    case 92 : 
    case 93 : 
    case 100 : 
    case 102 : 
    case 103 : 
    case 109 : 
        return "<YOUR SYNTAX ERROR MESSAGE HERE>\n";
    default:
      throw Caml_builtin_exceptions.not_found;
  }
}

exports.message = message;
/* No side effect */
