// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Jison = require("jison");

function to_parser(grammar) {
  return Curry._2((function(jison, grammar) { /* console.log(JSON.stringify(grammar, null, 4)); */ return new jison.Parser(grammar); }), Jison, grammar);
}

exports.to_parser = to_parser;
/* jison Not a pure module */
