// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function message(s) {
  switch (s) {
    case 4 : 
        return "Malformed sort declaration -- expected an operator, eg `add(arith; arith)`\n";
    case 31 : 
        return "Comma-separated list of identifiers (followed by a bracket) expected.\n";
    case 30 : 
    case 32 : 
        return "Identifier expected.\n";
    case 35 : 
        return "Expected a paren-enclosed list of valences.\n";
    case 36 : 
        return "Expected a valence.\n";
    case 3 : 
    case 12 : 
    case 13 : 
    case 14 : 
    case 15 : 
    case 18 : 
    case 19 : 
    case 20 : 
    case 25 : 
    case 26 : 
    case 27 : 
    case 28 : 
    case 29 : 
    case 33 : 
    case 34 : 
    case 37 : 
    case 38 : 
    case 39 : 
    case 40 : 
        throw Caml_builtin_exceptions.not_found;
    case 0 : 
    case 1 : 
    case 2 : 
    case 5 : 
    case 6 : 
    case 7 : 
    case 8 : 
    case 9 : 
    case 10 : 
    case 11 : 
    case 16 : 
    case 17 : 
    case 21 : 
    case 22 : 
    case 23 : 
    case 24 : 
    case 41 : 
    case 42 : 
        return "<YOUR SYNTAX ERROR MESSAGE HERE>\n";
    default:
      throw Caml_builtin_exceptions.not_found;
  }
}

exports.message = message;
/* No side effect */
